#pragma once

namespace ast {

enum class EntityType
{
    INVALID,
    FUNCTION,
    VARIABLE,
    VARIABLE_ASSIGN,
    POINTER_ASSIGN,
    ARRAY,
    ENUM_SPECIFIER,
    ENUMERATOR,
    POINTER,
    UNARY,
    STRUCT_DEC,
    STRUCT_SPECIFIER,
    SIZE_OF,
    STRING_DEFINITION,
    CHAR_DEFINITION,
    TYPEDEF_IDENTIFIER,
    TYPEDEF_DEC,
    CASE_STATEMENT,
    DEFAULT_STATEMENT,
    SCOPE,
    MULTI_LIST,
    SWITCH_STATEMENT,
    SEMICOLON,
    POINTER_DEREFERENCE,
    POINTER_ADDRESS
};

}
